
version: '3.8'

services: 
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=sistemahc
      - POSTGRES_USER=neil
      - POSTGRES_PASSWORD=admin123
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
# version: '3.8'
# services: 
#   basehc:
#     image: postgres:latest
#     restart: always
#     environment:
#       POSTGRES_DB: sistemahc
#       POSTGRES_USER: neil
#       POSTGRES_PASSWORD: admin123
#     ports:
#       - "5432:5432"
#     volumes:
#       - ./postgres_data:/var/lib/postgresql/data
#     networks:
#       redsistema:
#         ipv4_address: 172.28.0.10

#   backendhc:
#     environment:
#       - IP_DATABASE=172.28.0.10
#     build: .
#     ports:
#       - "4000:4000"
#     depends_on:
#       - basehc
#     networks:
#       redsistema:
#         ipv4_address: 172.28.0.20

# networks:
#   redsistema:
#     driver: bridge
#     ipam:
#       config:
#         - subnet: 172.28.0.0/16
#           gateway: 172.28.0.1


#version: '3.8'

# services:
#   basesistema:
#     image: postgres:latest
#     restart: always
#     environment:
#       - POSTGRES_DB=sistemahc
#       - POSTGRES_USER=neil
#       - POSTGRES_PASSWORD=admin123
#     ports:
#       - 5432:5432
#     volumes:
#       - ./postgres_data:/var/lib/postgresql/d
#   server:
#     build: .
#     restart: unless-stopped
#     ports:
#       - 4000:4000
#     environment:
#     - NODE_ENV
#     env_file:
#     - .env
#     volumes:
#       - .:/app
#     command: ["./wait-for-postgres.sh", "postgres", "npm", "run", "dev"]
#     depends_on:
#       - postgres