#Login
POST http://127.0.0.1:4000/auth/login
Content-Type: application/json
Accept: application/json

{
    "email": "neilgraneros11@gmail.com",
    "password": "123456"
}
###
POST http://127.0.0.1:4000/auth/login
Content-Type: application/json
Accept: application/json

{
    "email": "personal1@email.com",
    "password": "123456"
}

###
#Change 
POST http://127.0.0.1:4000/auth/change-password
Content-Type: application/json
Accept: application/json

{
    "token": "",
    "newPassword": ""
}
###
#Solicitar Correo
POST http://127.0.0.1:4000/auth/recovery
Content-Type: application/json
Accept: application/json

{
    "email": "neilgraneros11@gmail.com",
}

