@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsInJvbCI6InBlcnNvbmFsQWRtaW4iLCJpYXQiOjE2ODkwMDk3ODh9.YYgaILxeVVE85yB_UWUe8geIo-Np0VtPEOQOWEbXo_M

#listar
GET http://127.0.0.1:4000/personal/pacientes
Authorization: Bearer {{token}}
Accept: application/json

###
#obtener un usuario
GET http://127.0.0.1:4000/personal/3
Authorization: Bearer {{token}}
Accept: application/json

###
#crear
POST http://127.0.0.1:4000/personal/add-paciente
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
    "persona":{
      "nombre": "neil angel",
      "apellidoMaterno": "graneros",
      "apellidoPaterno": "flores",
      "ci": "12345687",
      "telefono": "152879522",
      "direccion": "villa copa ",
      "foto": "https://picsum.photos/id/237/200/300",
      "es_persona": true
    },
    "paciente":{
        "fechanac": "2000-06-11",
        "sexo": "masculino",
        "raza":"mestizo",
        "procedencia":"la paz",
        "residencia": "la paz"
    },
    "personalAdmin":{
        "personalAd_Id":1
    }
}