@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjUsInJvbCI6ImxhYm9yYXRvcmlzdGEiLCJpYXQiOjE3MDAyMzgyMDl9.EcdmVCrTCaYGd7skVGkTdL8hVq-S0nSfexuKPJ7namg

####################################################
###listar la historia del paciente de id x
GET http://127.0.0.1:4000/historia/1
Authorization: Bearer {{token}}
Accept: application/json

###listar la historia  de id x
GET http://127.0.0.1:4000/historia/form/1
Authorization: Bearer {{token}}
Accept: application/json

### ver nombre del laboratorista de id x
GET http://127.0.0.1:4000/historia/laboratorio/nombre/2
Authorization: Bearer {{token}}
Accept: application/json
###################################################################
### crear un laboratorio en la historia de id X
POST http://127.0.0.1:4000/historia/laboratorio/1
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
    "historiaLabo":{
        "examen": "a verrrr xd",
        "laboratoristaId": 1
    }
}
### editar un laboratorio de id x
PATCH http://127.0.0.1:4000/historia/laboratorio/1
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
    "historiaLabo":{
        "examen": "era bromaaa xd"
    }
}

### eliminar un laboratorio de id x
DELETE  http://127.0.0.1:4000/historia/laboratorio/5
Authorization: Bearer {{token}}
Accept: application/json