@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInJvbCI6ImFkbWluIiwiaWF0IjoxNjg5ODAxMDgwfQ.sYPl2dx0PIbBFXBBmEGeAQmw3p3iwI2SDSVj9CUNAEc

#listar usuario
GET http://127.0.0.1:4000/admin
Authorization: Bearer {{token}}
Accept: application/json

#eliminar usuario
DELETE http://127.0.0.1:4000/admin/4
Authorization: Bearer {{token}}
Accept: application/json
###########################################################
### doctores
GET http://127.0.0.1:4000/admin/doctor?q=&page=1&limit=10
Authorization: Bearer {{token}}
Accept: application/json

### mostrar un doctor
GET http://127.0.0.1:4000/admin/doctor/7
Authorization: Bearer {{token}}
Accept: application/json
### crear un doctor
POST http://127.0.0.1:4000/admin/doctor
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
    "usuario": {
      "email":"doctor11@email.com",
      "password": "123456",
      "rol": "doctor"
    },
    "persona":{
      "nombre": "juan carlos",
      "apellidoMaterno": "flores",
      "apellidoPaterno": "ortiz",
      "ci": "12345687",
      "telefono": "152879522",
      "direccion": "villa copa ",
      "foto": "https://picsum.photos/id/237/200/300",
      "es_persona": false
    },
    "doctor":{
      "unidad":"genetica",
      "especialidad": "genetica medica",
      "numeroMatricula": "111"
    }
}
### Editar un doctor
PATCH  http://127.0.0.1:4000/admin/doctor/7
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
    "usuario": {
      "email":"doctor22@email.com"
    },
    "persona":{
      "nombre": "gary nova mamani",
      "apellidoPaterno": "blanco"
    },
    "doctor":{
      "unidad":"genetica lab",
      "numeroMatricula": "4646546"
    }
}
### eliminar un doctor
DELETE http://127.0.0.1:4000/admin/doctor/6
Authorization: Bearer {{token}}
Accept: application/json

###############################################fin doctores
### listar personal
GET http://127.0.0.1:4000/admin/personalAd?q=&page=1&limit=10
Authorization: Bearer {{token}}
Accept: application/json

### mostrar un personalAd
GET http://127.0.0.1:4000/admin/personalAd/2
Authorization: Bearer {{token}}
Accept: application/json

### crear un personalAd
POST http://127.0.0.1:4000/admin/personalAd
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
    "usuario": {
      "email":"personal1@email.com",
      "password": "123456",
      "rol": "personalAdmin"
    },
    "persona":{
      "nombre": "Dianna Petty",
      "apellidoMaterno": "Hayes",
      "apellidoPaterno": "Mccormick",
      "ci": "12345687",
      "telefono": "152879522",
      "direccion": "villa copa ",
      "foto": "http://placehold.it/32x32",
      "es_persona": false
    },
    "personalAdmin":{
      "cargo":"secretaria"
    }
}
### Editar un personalAd
PATCH  http://127.0.0.1:4000/admin/personalAd/2
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
    "usuario": {
      "email":"personal22@email.com"
    },
    "persona":{
      "nombre": "alejandra gabriela"
    },
    "personalAdmin":{
      "cargo":"mensajera"
    }
}
### eliminar un personalAd
DELETE http://127.0.0.1:4000/admin/personalAd/2
Authorization: Bearer {{token}}
Accept: application/json
###############################################fin personalAd
### listar laboratoristas
GET http://127.0.0.1:4000/admin/laboratorista?q=&page=1&limit=10
Authorization: Bearer {{token}}
Accept: application/json

### mostrar un laboratorista
GET http://127.0.0.1:4000/admin/laboratorista/2
Authorization: Bearer {{token}}
Accept: application/json

### crear un laboratorista
POST http://127.0.0.1:4000/admin/laboratorista
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
    "usuario": {
      "email":"laboratorista1@email.com",
      "password": "123456",
      "rol": "laboratorista"
    },
    "persona":{
      "nombre": "Jeri Bradford",
      "apellidoMaterno": "Gilliam",
      "apellidoPaterno": "Holder",
      "ci": "12345687",
      "telefono": "152879522",
      "direccion": "villa copa ",
      "foto": "http://placehold.it/32x32",
      "es_persona": false
    },
    "laboratorista":{
      "especialidad": "laboratorio medico",
      "matriculaProf": "1111"
    }
}
### Editar un laboratorista
PATCH  http://127.0.0.1:4000/admin/laboratorista/2
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
    "usuario": {
      "email":"laboratorista22@email.com"
    },
    "persona":{
      "nombre": "diego marco"
    },
    "laboratorista":{
      "especialidad": "laboratorio de huesos"
    }
}
### eliminar un laboratorista
DELETE http://127.0.0.1:4000/admin/laboratorista/2
Authorization: Bearer {{token}}
Accept: application/json
###
